' ############################################################################
' #                                                                          #
' # Delta Azure 4+1 PlantUML Stylesheet - Darker theme                       #
' #                                                                          #
' # Author: AGS                                                              #
' # Date: 15 Feb 2021                                                        #
' # Uses: Azure-PlantUML, version 2.1.0                                      #
' # See: https://github.com/RicardoNiepel/Azure-PlantUML                     #
' ############################################################################

!define AZURE_BG_COLOR #3F3F3F
!define AZURE_BORDER_COLOR #0070C0

skinparam backgroundColor AZURE_BG_COLOR

skinparam package {
  BackgroundColor #003E6C
  FontColor White
}

skinparam note {
  BorderColor White
  BackgroundColor AZURE_BG_COLOR
  FontColor White
}
skinparam Arrow {
  Color White
  FontColor White
  FontSize 12
  ArrowFontStyle Bold
}
